name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # TODO: what version do we want?
          distribution: 'adopt'
          cache: maven

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # TODO: what version do we want?
          # cache: npm # TODO: requires package-lock.json

      - name: Build with Maven
        run: mvn install

      - name: Build with NPM
        working-directory: ./vscode
        run: npm install

      - name: Set up VSCE
        run: npm install -g @vscode/vsce

      - name: Build with VSCE
        working-directory: ./vscode
        run: vsce package

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: gobpie-plugin
          path: ./vscode/gobpie-*.vsix
